spark:
  app: "Masterarbeit"
  master: 10.28.0.25
  port: 7077
train:
  ratings: s3://location.csv
  header: true
  training: 0.6
  validation: 0.6
  test: 0.6
  ranks: [8, 16, 200]
  lambdas: [0.2, 0.1]
  iterations: [5,10,20,25]
  model: MatrixFactorizationModel
